INSERT INTO airline_ref(airline_id,airline_name) VALUES (1,'ATA Airlines (TZ)');
INSERT INTO airline_ref(airline_id,airline_name) VALUES (2,'AirTran Airways (FL)');
INSERT INTO airline_ref(airline_id,airline_name) VALUES (3,'Alaska Airlines Inc. (AS)');
INSERT INTO airline_ref(airline_id,airline_name) VALUES (4,'Allegiant Air (G4)');
INSERT INTO airline_ref(airline_id,airline_name) VALUES (5,'Aloha Airlines Inc. (AQ)');
INSERT INTO airline_ref(airline_id,airline_name) VALUES (6,'America West Airlines Inc. (HP)');
INSERT INTO airline_ref(airline_id,airline_name) VALUES (7,'American Airlines Inc. (AA)');
INSERT INTO airline_ref(airline_id,airline_name) VALUES (8,'American Eagle Airlines Inc. (MQ)');
INSERT INTO airline_ref(airline_id,airline_name) VALUES (9,'Atlantic Coast Airlines (DH)');
INSERT INTO airline_ref(airline_id,airline_name) VALUES (10,'Atlantic Southeast Airlines (EV)');
INSERT INTO airline_ref(airline_id,airline_name) VALUES (11,'Comair Inc. (OH)');
INSERT INTO airline_ref(airline_id,airline_name) VALUES (12,'Continental Airlines Inc. (CO)');
INSERT INTO airline_ref(airline_id,airline_name) VALUES (13,'Delta Airlines Inc. (DL)');
INSERT INTO airline_ref(airline_id,airline_name) VALUES (14,'Endeavor Air Inc. (9E)');
INSERT INTO airline_ref(airline_id,airline_name) VALUES (15,'Envoy Air (MQ)');
INSERT INTO airline_ref(airline_id,airline_name) VALUES (16,'ExpressJet Airlines Inc. (EV)');
INSERT INTO airline_ref(airline_id,airline_name) VALUES (17,'ExpressJet Airlines Inc. (XE)');
INSERT INTO airline_ref(airline_id,airline_name) VALUES (18,'ExpressJet Airlines LLC (EV)');
INSERT INTO airline_ref(airline_id,airline_name) VALUES (19,'Frontier Airlines Inc. (F9)');
INSERT INTO airline_ref(airline_id,airline_name) VALUES (20,'Hawaiian Airlines Inc. (HA)');
INSERT INTO airline_ref(airline_id,airline_name) VALUES (21,'Independence Air (DH)');
INSERT INTO airline_ref(airline_id,airline_name) VALUES (22,'JetBlue Airways (B6)');
INSERT INTO airline_ref(airline_id,airline_name) VALUES (23,'Mesa Airlines Inc. (YV)');
INSERT INTO airline_ref(airline_id,airline_name) VALUES (24,'Northwest Airlines Inc. (NW)');
INSERT INTO airline_ref(airline_id,airline_name) VALUES (25,'PSA Airlines Inc. (OH)');
INSERT INTO airline_ref(airline_id,airline_name) VALUES (26,'Pinnacle Airlines Inc. (9E)');
INSERT INTO airline_ref(airline_id,airline_name) VALUES (27,'Republic Airline (YX)');
INSERT INTO airline_ref(airline_id,airline_name) VALUES (28,'SkyWest Airlines Inc. (OO)');
INSERT INTO airline_ref(airline_id,airline_name) VALUES (29,'Southwest Airlines Co. (WN)');
INSERT INTO airline_ref(airline_id,airline_name) VALUES (30,'Spirit Airlines (NK)');
INSERT INTO airline_ref(airline_id,airline_name) VALUES (31,'US Airways Inc. (US)');
INSERT INTO airline_ref(airline_id,airline_name) VALUES (32,'United Airlines Inc. (UA)');
INSERT INTO airline_ref(airline_id,airline_name) VALUES (33,'Virgin America (VX)');
commit;
