INSERT INTO airport_ref(airport_id,airport_name) VALUES (1,'Aberdeen, SD: Aberdeen Regional (ABR)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (2,'Abilene, TX: Abilene Regional (ABI)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (3,'Adak Island, AK: Adak (ADK)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (4,'Aguadilla, PR: Rafael Hernandez (BQN)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (5,'Akron, OH: Akron-Canton Regional (CAK)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (6,'Albany, GA: Southwest Georgia Regional (ABY)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (7,'Albany, NY: Albany International (ALB)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (8,'Albuquerque, NM: Albuquerque International Sunport (ABQ)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (9,'Alexandria, LA: Alexandria International (AEX)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (10,'Allentown/Bethlehem/Easton, PA: Lehigh Valley International (ABE)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (11,'Alpena, MI: Alpena County Regional (APN)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (12,'Amarillo, TX: Rick Husband Amarillo International (AMA)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (13,'Anchorage, AK: Ted Stevens Anchorage International (ANC)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (14,'Aniak, AK: Aniak Airport (ANI)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (15,'Appleton, WI: Appleton International (ATW)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (16,'Arcata/Eureka, CA: California Redwood Coast Humboldt County (ACV)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (17,'Asheville, NC: Asheville Regional (AVL)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (18,'Ashland, WV: Tri-State/Milton J. Ferguson Field (HTS)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (19,'Aspen, CO: Aspen Pitkin County Sardy Field (ASE)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (20,'Atlanta, GA: Hartsfield-Jackson Atlanta International (ATL)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (21,'Atlantic City, NJ: Atlantic City International (ACY)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (22,'Augusta, GA: Augusta Regional at Bush Field (AGS)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (23,'Austin, TX: Austin - Bergstrom International (AUS)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (24,'Austin, TX: Robert Mueller Municipal (AUS)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (25,'Bakersfield, CA: Meadows Field (BFL)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (26,'Baltimore, MD: Baltimore/Washington International Thurgood Marshall (BWI)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (27,'Bangor, ME: Bangor International (BGR)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (28,'Barrow, AK: Wiley Post/Will Rogers Memorial (BRW)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (29,'Baton Rouge, LA: Baton Rouge Metropolitan/Ryan Field (BTR)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (30,'Beaumont/Port Arthur, TX: Jack Brooks Regional (BPT)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (31,'Belleville, IL: Scott AFB/MidAmerica (BLV)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (32,'Bellingham, WA: Bellingham International (BLI)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (33,'Bemidji, MN: Bemidji Regional (BJI)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (34,'Bend/Redmond, OR: Roberts Field (RDM)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (35,'Bethel, AK: Bethel Airport (BET)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (36,'Billings, MT: Billings Logan International (BIL)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (37,'Binghamton, NY: Greater Binghamton/Edwin A. Link Field (BGM)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (38,'Birmingham, AL: Birmingham-Shuttlesworth International (BHM)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (39,'Bismarck/Mandan, ND: Bismarck Municipal (BIS)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (40,'Bloomington/Normal, IL: Central Illinois Regional (BMI)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (41,'Boise, ID: Boise Air Terminal (BOI)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (42,'Boston, MA: Logan International (BOS)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (43,'Bozeman, MT: Bozeman Yellowstone International (BZN)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (44,'Brainerd, MN: Brainerd Lakes Regional (BRD)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (45,'Branson, MO: Branson Airport (BKG)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (46,'Bristol/Johnson City/Kingsport, TN: Tri Cities (TRI)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (47,'Brownsville, TX: Brownsville South Padre Island International (BRO)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (48,'Brunswick, GA: Brunswick Golden Isles (BQK)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (49,'Buffalo, NY: Buffalo Niagara International (BUF)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (50,'Bullhead City, AZ: Laughlin/Bullhead International (IFP)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (51,'Burbank, CA: Bob Hope (BUR)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (52,'Burlington, VT: Burlington International (BTV)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (53,'Butte, MT: Bert Mooney (BTM)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (54,'CONCORD, NC: Concord Padgett Regional (USA)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (55,'Cape Girardeau, MO: Cape Girardeau Regional (CGI)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (56,'Carlsbad, CA: McClellan-Palomar (CLD)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (57,'Casper, WY: Casper/Natrona County International (CPR)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (58,'Cedar City, UT: Cedar City Regional (CDC)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (59,'Cedar Rapids/Iowa City, IA: The Eastern Iowa (CID)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (60,'Champaign/Urbana, IL: University of Illinois/Willard (CMI)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (61,'Charleston, SC: Charleston AFB/International (CHS)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (62,'Charleston/Dunbar, WV: Yeager (CRW)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (63,'Charlotte Amalie, VI: Cyril E King (STT)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (64,'Charlotte, NC: Charlotte Douglas International (CLT)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (65,'Charlottesville, VA: Charlottesville Albemarle (CHO)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (66,'Chattanooga, TN: Lovell Field (CHA)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (67,'Cheyenne, WY: Cheyenne Regional/Jerry Olson Field (CYS)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (68,'Chicago, IL: Chicago Midway International (MDW)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (69,'Chicago, IL: Chicago O&#39;Hare International (ORD)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (70,'Chico, CA: Chico Municipal (CIC)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (71,'Christiansted, VI: Henry E. Rohlsen (STX)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (72,'Cincinnati, OH: Cincinnati/Northern Kentucky International (CVG)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (73,'Clarksburg/Fairmont, WV: North Central West Virginia (CKB)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (74,'Cleveland, OH: Cleveland-Hopkins International (CLE)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (75,'Cody, WY: Yellowstone Regional (COD)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (76,'College Station/Bryan, TX: Easterwood Field (CLL)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (77,'Colorado Springs, CO: City of Colorado Springs Municipal (COS)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (78,'Columbia, MO: Columbia Regional (COU)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (79,'Columbia, SC: Columbia Metropolitan (CAE)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (80,'Columbus, GA: Columbus Airport (CSG)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (81,'Columbus, MS: Columbus AFB (CBM)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (82,'Columbus, MS: Golden Triangle Regional (GTR)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (83,'Columbus, OH: John Glenn Columbus International (CMH)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (84,'Columbus, OH: Rickenbacker International (LCK)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (85,'Concord, CA: Buchanan Field (CCR)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (86,'Cordova, AK: Merle K Mudhole Smith (CDV)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (87,'Corpus Christi, TX: Corpus Christi International (CRP)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (88,'Crescent City, CA: Jack McNamara Field (CEC)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (89,'Dallas, TX: Dallas Love Field (DAL)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (90,'Dallas/Fort Worth, TX: Dallas/Fort Worth International (DFW)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (91,'Dayton, OH: James M Cox/Dayton International (DAY)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (92,'Daytona Beach, FL: Daytona Beach International (DAB)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (93,'Deadhorse, AK: Deadhorse Airport (SCC)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (94,'Del Rio, TX: Del Rio International (DRT)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (95,'Denver, CO: Denver International (DEN)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (96,'Des Moines, IA: Des Moines International (DSM)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (97,'Detroit, MI: Coleman A. Young Municipal (DET)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (98,'Detroit, MI: Detroit Metro Wayne County (DTW)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (99,'Devils Lake, ND: Devils Lake Regional (DVL)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (100,'Dickinson, ND: Dickinson - Theodore Roosevelt Regional (DIK)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (101,'Dillingham, AK: Dillingham Airport (DLG)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (102,'Dothan, AL: Dothan Regional (DHN)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (103,'Dubuque, IA: Dubuque Regional (DBQ)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (104,'Duluth, MN: Duluth International (DLH)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (105,'Durango, CO: Durango La Plata County (DRO)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (106,'Eagle, CO: Eagle County Regional (EGE)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (107,'Eau Claire, WI: Chippewa Valley Regional (EAU)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (108,'El Centro, CA: Imperial County (IPL)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (109,'El Paso, TX: El Paso International (ELP)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (110,'Elko, NV: Elko Regional (EKO)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (111,'Elmira/Corning, NY: Elmira/Corning Regional (ELM)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (112,'Erie, PA: Erie International/Tom Ridge Field (ERI)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (113,'Escanaba, MI: Delta County (ESC)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (114,'Eugene, OR: Mahlon Sweet Field (EUG)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (115,'Evansville, IN: Evansville Regional (EVV)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (116,'Everett, WA: Snohomish County (PAE)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (117,'Fairbanks, AK: Fairbanks International (FAI)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (118,'Fargo, ND: Hector International (FAR)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (119,'Farmington, NM: Four Corners Regional (FMN)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (120,'Fayetteville, AR: Northwest Arkansas Regional (XNA)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (121,'Fayetteville, NC: Fayetteville Regional/Grannis Field (FAY)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (122,'Flagstaff, AZ: Flagstaff Pulliam (FLG)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (123,'Flint, MI: Bishop International (FNT)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (124,'Florence, SC: Florence Regional (FLO)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (125,'Fort Collins/Loveland, CO: Northern Colorado Regional (FNL)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (126,'Fort Lauderdale, FL: Fort Lauderdale-Hollywood International (FLL)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (127,'Fort Myers, FL: Southwest Florida International (RSW)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (128,'Fort Smith, AR: Fort Smith Regional (FSM)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (129,'Fort Wayne, IN: Fort Wayne International (FWA)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (130,'Fresno, CA: Fresno Yosemite International (FAT)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (131,'Gainesville, FL: Gainesville Regional (GNV)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (132,'Garden City, KS: Garden City Regional (GCK)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (133,'Gillette, WY: Gillette Campbell County (GCC)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (134,'Grand Canyon, AZ: Grand Canyon National Park (GCN)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (135,'Grand Forks, ND: Grand Forks International (GFK)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (136,'Grand Island, NE: Central Nebraska Regional (GRI)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (137,'Grand Junction, CO: Grand Junction Regional (GJT)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (138,'Grand Rapids, MI: Gerald R. Ford International (GRR)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (139,'Great Falls, MT: Great Falls International (GTF)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (140,'Green Bay, WI: Green Bay Austin Straubel International (GRB)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (141,'Greensboro/High Point, NC: Piedmont Triad International (GSO)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (142,'Greenville, MS: Greenville Mid Delta (GLH)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (143,'Greenville, NC: Pitt Greenville (PGV)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (144,'Greer, SC: Greenville-Spartanburg International (GSP)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (145,'Guam, TT: Guam International (GUM)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (146,'Gulfport/Biloxi, MS: Gulfport-Biloxi International (GPT)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (147,'Gunnison, CO: Gunnison-Crested Butte Regional (GUC)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (148,'Gustavus, AK: Gustavus Airport (GST)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (149,'Hagerstown, MD: Hagerstown Regional-Richard A. Henson Field (HGR)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (150,'Hancock/Houghton, MI: Houghton County Memorial (CMX)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (151,'Harlingen/San Benito, TX: Valley International (HRL)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (152,'Harrisburg, PA: Harrisburg International (MDT)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (153,'Hartford, CT: Bradley International (BDL)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (154,'Hattiesburg/Laurel, MS: Hattiesburg-Laurel Regional (PIB)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (155,'Hayden, CO: Yampa Valley (HDN)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (156,'Hays, KS: Hays Regional (HYS)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (157,'Helena, MT: Helena Regional (HLN)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (158,'Hibbing, MN: Range Regional (HIB)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (159,'Hickory, NC: Hickory Regional (HKY)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (160,'Hilo, HI: Hilo International (ITO)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (161,'Hilton Head, SC: Hilton Head Airport (HHH)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (162,'Hobbs, NM: Lea County Regional (HOB)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (163,'Honolulu, HI: Daniel K Inouye International (HNL)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (164,'Hoolehua, HI: Molokai (MKK)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (165,'Houston, TX: Ellington (EFD)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (166,'Houston, TX: George Bush Intercontinental/Houston (IAH)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (167,'Houston, TX: William P Hobby (HOU)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (168,'Huntsville, AL: Huntsville International-Carl T Jones Field (HSV)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (169,'Hyannis, MA: Barnstable Municipal-Boardman/Polando Field (HYA)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (170,'Idaho Falls, ID: Idaho Falls Regional (IDA)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (171,'Indianapolis, IN: Indianapolis International (IND)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (172,'International Falls, MN: Falls International Einarson Field (INL)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (173,'Inyokern, CA: Inyokern Airport (IYK)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (174,'Iron Mountain/Kingsfd, MI: Ford (IMT)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (175,'Islip, NY: Long Island MacArthur (ISP)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (176,'Ithaca/Cortland, NY: Ithaca Tompkins Regional (ITH)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (177,'Jackson, WY: Jackson Hole (JAC)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (178,'Jackson/Vicksburg, MS: Jackson Medgar Wiley Evers International (JAN)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (179,'Jacksonville, FL: Jacksonville International (JAX)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (180,'Jacksonville/Camp Lejeune, NC: Albert J Ellis (OAJ)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (181,'Jamestown, ND: Jamestown Regional (JMS)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (182,'Joplin, MO: Joplin Regional (JLN)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (183,'Juneau, AK: Juneau International (JNU)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (184,'Kahului, HI: Kahului Airport (OGG)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (185,'Kalamazoo, MI: Kalamazoo/Battle Creek International (AZO)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (186,'Kalispell, MT: Glacier Park International (FCA)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (187,'Kansas City, MO: Charles B. Wheeler Downtown (MKC)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (188,'Kansas City, MO: Kansas City International (MCI)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (189,'Kearney, NE: Kearney Regional (EAR)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (190,'Ketchikan, AK: Ketchikan International (KTN)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (191,'Key West, FL: Key West International (EYW)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (192,'Killeen, TX: Robert Gray AAF (GRK)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (193,'Killeen, TX: Skylark Field (ILE)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (194,'King Salmon, AK: King Salmon Airport (AKN)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (195,'Kinston, NC: Kinston Regional Jetport at Stallings Field (ISO)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (196,'Klamath Falls, OR: Crater Lake Klamath Regional (LMT)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (197,'Knoxville, TN: McGhee Tyson (TYS)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (198,'Kodiak, AK: Kodiak Airport (ADQ)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (199,'Kona, HI: Ellison Onizuka Kona International at Keahole (KOA)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (200,'Koror, Palau: Babelthuap (ROR)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (201,'Kotzebue, AK: Ralph Wien Memorial (OTZ)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (202,'La Crosse, WI: La Crosse Regional (LSE)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (203,'Lafayette, LA: Lafayette Regional Paul Fournet Field (LFT)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (204,'Lake Charles, LA: Lake Charles Regional (LCH)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (205,'Lake Tahoe, CA: Lake Tahoe Airport (TVL)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (206,'Lanai, HI: Lanai Airport (LNY)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (207,'Lansing, MI: Capital Region International (LAN)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (208,'Laramie, WY: Laramie Regional (LAR)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (209,'Laredo, TX: Laredo International (LRD)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (210,'Las Vegas, NV: McCarran International (LAS)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (211,'Latrobe, PA: Arnold Palmer Regional (LBE)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (212,'Lawton/Fort Sill, OK: Lawton-Fort Sill Regional (LAW)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (213,'Lewisburg, WV: Greenbrier Valley (LWB)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (214,'Lewiston, ID: Lewiston Nez Perce County (LWS)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (215,'Lexington, KY: Blue Grass (LEX)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (216,'Liberal, KS: Liberal Mid-America Regional (LBL)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (217,'Lihue, HI: Lihue Airport (LIH)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (218,'Lincoln, NE: Lincoln Airport (LNK)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (219,'Little Rock, AR: Bill and Hillary Clinton Nat Adams Field (LIT)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (220,'Long Beach, CA: Long Beach Airport (LGB)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (221,'Longview, TX: East Texas Regional (GGG)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (222,'Los Angeles, CA: Los Angeles International (LAX)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (223,'Louisville, KY: Louisville International-Standiford Field (SDF)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (224,'Lubbock, TX: Lubbock Preston Smith International (LBB)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (225,'Lynchburg, VA: Lynchburg Regional/Preston Glenn Field (LYH)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (226,'Macon, GA: Middle Georgia Regional (MCN)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (227,'Madison, WI: Dane County Regional-Truax Field (MSN)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (228,'Mammoth Lakes, CA: Mammoth Lakes Airport (MMH)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (229,'Manchester, NH: Manchester-Boston Regional (MHT)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (230,'Manhattan/Ft. Riley, KS: Manhattan Regional (MHK)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (231,'Marathon, FL: The Florida Keys Marathon International (MTH)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (232,'Marquette, MI: Sawyer International (MQT)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (233,'Martha&#39;s Vineyard, MA: Martha&#39;s Vineyard Airport (MVY)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (234,'Mayaguez, PR: Eugenio Maria de Hostos (MAZ)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (235,'Medford, OR: Rogue Valley International - Medford (MFR)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (236,'Melbourne, FL: Melbourne International (MLB)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (237,'Memphis, TN: Memphis International (MEM)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (238,'Meridian, MS: Key Field (MEI)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (239,'Miami, FL: Miami International (MIA)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (240,'Midland/Odessa, TX: Midland International Air and Space Port (MAF)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (241,'Milwaukee, WI: General Mitchell International (MKE)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (242,'Minneapolis, MN: Minneapolis-St Paul International (MSP)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (243,'Minot, ND: Minot AFB (MIB)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (244,'Minot, ND: Minot International (MOT)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (245,'Mission/McAllen/Edinburg, TX: McAllen Miller International (MFE)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (246,'Missoula, MT: Missoula International (MSO)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (247,'Moab, UT: Canyonlands Field (CNY)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (248,'Mobile, AL: Mobile Downtown (BFM)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (249,'Mobile, AL: Mobile Regional (MOB)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (250,'Modesto, CA: Modesto City-County-Harry Sham Field (MOD)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (251,'Moline, IL: Quad City International (MLI)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (252,'Monroe, LA: Monroe Regional (MLU)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (253,'Monterey, CA: Monterey Regional (MRY)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (254,'Montgomery, AL: Montgomery Regional (MGM)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (255,'Montrose/Delta, CO: Montrose Regional (MTJ)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (256,'Moses Lake, WA: Grant County International (MWH)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (257,'Mosinee, WI: Central Wisconsin (CWA)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (258,'Muskegon, MI: Muskegon County (MKG)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (259,'Myrtle Beach, SC: Myrtle Beach International (MYR)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (260,'Nantucket, MA: Nantucket Memorial (ACK)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (261,'Naples, FL: Naples Municipal (APF)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (262,'Nashville, TN: Nashville International (BNA)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (263,'New Bern/Morehead/Beaufort, NC: Coastal Carolina Regional (EWN)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (264,'New Haven, CT: Tweed New Haven (HVN)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (265,'New Orleans, LA: Louis Armstrong New Orleans International (MSY)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (266,'New York, NY: John F. Kennedy International (JFK)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (267,'New York, NY: LaGuardia (LGA)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (268,'Newark, NJ: Newark Liberty International (EWR)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (269,'Newburgh/Poughkeepsie, NY: Stewart International (SWF)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (270,'Newport News/Williamsburg, VA: Newport News/Williamsburg International (PHF)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (271,'Niagara Falls, NY: Niagara Falls International (IAG)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (272,'Nome, AK: Nome Airport (OME)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (273,'Norfolk, VA: Norfolk International (ORF)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (274,'North Bend/Coos Bay, OR: Southwest Oregon Regional (OTH)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (275,'North Platte, NE: North Platte Regional Airport Lee Bird Field (LBF)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (276,'Oakland, CA: Metropolitan Oakland International (OAK)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (277,'Ogden, UT: Ogden-Hinckley (OGD)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (278,'Ogdensburg, NY: Ogdensburg International (OGS)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (279,'Oklahoma City, OK: Will Rogers World (OKC)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (280,'Omaha, NE: Eppley Airfield (OMA)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (281,'Ontario, CA: Ontario International (ONT)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (282,'Orlando, FL: Orlando International (MCO)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (283,'Owensboro, KY: Owensboro Daviess County Regional (OWB)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (284,'Oxnard/Ventura, CA: Oxnard (OXR)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (285,'Paducah, KY: Barkley Regional (PAH)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (286,'Pago Pago, TT: Pago Pago International (PPG)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (287,'Palm Springs, CA: Palm Springs International (PSP)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (288,'Palmdale, CA: Palmdale USAF Plant 42 (PMD)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (289,'Panama City, FL: Bay County (PFN)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (290,'Panama City, FL: Northwest Florida Beaches International (ECP)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (291,'Pasco/Kennewick/Richland, WA: Tri Cities (PSC)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (292,'Pellston, MI: Pellston Regional Airport of Emmet County (PLN)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (293,'Pensacola, FL: Pensacola International (PNS)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (294,'Peoria, IL: General Downing - Peoria International (PIA)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (295,'Petersburg, AK: Petersburg James A Johnson (PSG)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (296,'Philadelphia, PA: Philadelphia International (PHL)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (297,'Phoenix, AZ: Phoenix - Mesa Gateway (AZA)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (298,'Phoenix, AZ: Phoenix Sky Harbor International (PHX)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (299,'Pierre, SD: Pierre Regional (PIR)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (300,'Pinehurst/Southern Pines, NC: Moore County (SOP)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (301,'Pittsburgh, PA: Pittsburgh International (PIT)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (302,'Plattsburgh, NY: Plattsburgh International (PBG)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (303,'Pocatello, ID: Pocatello Regional (PIH)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (304,'Ponce, PR: Mercedita (PSE)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (305,'Portland, ME: Portland International Jetport (PWM)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (306,'Portland, OR: Portland International (PDX)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (307,'Portsmouth, NH: Portsmouth International at Pease (PSM)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (308,'Prescott, AZ: Ernest A. Love Field (PRC)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (309,'Providence, RI: Theodore Francis Green State (PVD)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (310,'Provo, UT: Provo Municipal (PVU)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (311,'Pueblo, CO: Pueblo Memorial (PUB)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (312,'Punta Gorda, FL: Punta Gorda Airport (PGD)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (313,'Quincy, IL: Quincy Regional-Baldwin Field (UIN)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (314,'Raleigh/Durham, NC: Raleigh-Durham International (RDU)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (315,'Rapid City, SD: Ellsworth AFB (RCA)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (316,'Rapid City, SD: Rapid City Regional (RAP)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (317,'Red River, ND: Grand Forks AFB (RDR)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (318,'Redding, CA: Redding Municipal (RDD)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (319,'Reno, NV: Reno/Tahoe International (RNO)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (320,'Rhinelander, WI: Rhinelander/Oneida County (RHI)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (321,'Richmond, VA: Richmond International (RIC)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (322,'Roanoke, VA: Roanoke Blacksburg Regional Woodrum Field (ROA)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (323,'Rochester, MN: Rochester International (RST)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (324,'Rochester, NY: Greater Rochester International (ROC)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (325,'Rock Springs, WY: Southwest Wyoming Regional (RKS)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (326,'Rockford, IL: Chicago/Rockford International (RFD)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (327,'Roswell, NM: Roswell International Air Center (ROW)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (328,'Rota, TT: Benjamin Taisacan Manglona International (ROP)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (329,'Sacramento, CA: Sacramento International (SMF)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (330,'Saginaw/Bay City/Midland, MI: MBS International (MBS)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (331,'Saipan, TT: Francisco C. Ada Saipan International (SPN)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (332,'Salem, OR: McNary Field (SLE)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (333,'Salina, KS: Salina Regional (SLN)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (334,'Salt Lake City, UT: Salt Lake City International (SLC)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (335,'San Angelo, TX: San Angelo Regional/Mathis Field (SJT)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (336,'San Antonio, TX: San Antonio International (SAT)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (337,'San Diego, CA: San Diego International (SAN)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (338,'San Francisco, CA: San Francisco International (SFO)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (339,'San Jose, CA: Norman Y. Mineta San Jose International (SJC)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (340,'San Juan, PR: Luis Munoz Marin International (SJU)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (341,'San Luis Obispo, CA: San Luis County Regional (SBP)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (342,'Sanford, FL: Orlando Sanford International (SFB)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (343,'Santa Ana, CA: John Wayne Airport-Orange County (SNA)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (344,'Santa Barbara, CA: Santa Barbara Municipal (SBA)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (345,'Santa Fe, NM: Santa Fe Municipal (SAF)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (346,'Santa Maria, CA: Santa Maria Public/Capt. G. Allan Hancock Field (SMX)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (347,'Santa Rosa, CA: Charles M. Schulz - Sonoma County (STS)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (348,'Sarasota/Bradenton, FL: Sarasota/Bradenton International (SRQ)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (349,'Sault Ste. Marie, MI: Chippewa County International (CIU)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (350,'Savannah, GA: Savannah/Hilton Head International (SAV)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (351,'Scottsbluff, NE: Western Neb. Regional/William B. Heilig Field (BFF)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (352,'Scranton/Wilkes-Barre, PA: Wilkes Barre Scranton International (AVP)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (353,'Seattle, WA: Boeing Field/King County International (BFI)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (354,'Seattle, WA: Seattle/Tacoma International (SEA)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (355,'Shreveport, LA: Shreveport Regional (SHV)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (356,'Sioux City, IA: Sioux Gateway/Col. Bud Day Field (SUX)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (357,'Sioux Falls, SD: Joe Foss Field (FSD)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (358,'Sitka, AK: Sitka Rocky Gutierrez (SIT)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (359,'South Bend, IN: South Bend International (SBN)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (360,'Spokane, WA: Fairchild AFB (SKA)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (361,'Spokane, WA: Spokane International (GEG)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (362,'Springfield, IL: Abraham Lincoln Capital (SPI)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (363,'Springfield, MO: Springfield-Branson National (SGF)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (364,'St. Augustine, FL: Northeast Florida Regional (UST)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (365,'St. Cloud, MN: St. Cloud Regional (STC)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (366,'St. George, UT: St George Regional (SGU)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (367,'St. Louis, MO: St Louis Lambert International (STL)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (368,'St. Mary&#39;s, AK: St. Mary&#39;s Airport (KSM)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (369,'St. Petersburg, FL: St Pete Clearwater International (PIE)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (370,'State College, PA: University Park (SCE)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (371,'Staunton, VA: Shenandoah Valley Regional (SHD)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (372,'Stillwater, OK: Stillwater Regional (SWO)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (373,'Stockton, CA: Stockton Metropolitan (SCK)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (374,'Sun Valley/Hailey/Ketchum, ID: Friedman Memorial (SUN)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (375,'Syracuse, NY: Syracuse Hancock International (SYR)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (376,'Tallahassee, FL: Tallahassee International (TLH)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (377,'Tampa, FL: Tampa International (TPA)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (378,'Telluride, CO: Telluride Regional (TEX)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (379,'Texarkana, AR: Texarkana Regional-Webb Field (TXK)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (380,'Tokeen, AK: Tokeen Airport (TKI)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (381,'Toledo, OH: Toledo Express (TOL)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (382,'Topeka, KS: Topeka Regional (FOE)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (383,'Traverse City, MI: Cherry Capital (TVC)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (384,'Trenton, NJ: Trenton Mercer (TTN)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (385,'Tucson, AZ: Tucson International (TUS)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (386,'Tulsa, OK: Tulsa International (TUL)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (387,'Tunica, MS: Tunica Municipal (UTM)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (388,'Tupelo, MS: Tupelo Regional (TUP)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (389,'Twin Falls, ID: Joslin Field - Magic Valley Regional (TWF)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (390,'Tyler, TX: Tyler Pounds Regional (TYR)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (391,'Unalaska, AK: Unalaska Airport (DUT)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (392,'Utica/Rome, NY: Oneida County (UCA)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (393,'Valdosta, GA: Valdosta Regional (VLD)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (394,'Valparaiso, FL: Eglin AFB Destin Fort Walton Beach (VPS)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (395,'Vernal, UT: Vernal Regional (VEL)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (396,'Victoria, TX: Victoria Regional (VCT)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (397,'Visalia, CA: Visalia Municipal (VIS)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (398,'Waco, TX: Waco Regional (ACT)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (399,'Washington, DC: Ronald Reagan Washington National (DCA)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (400,'Washington, DC: Washington Dulles International (IAD)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (401,'Waterloo, IA: Waterloo Regional (ALO)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (402,'Watertown, NY: Watertown International (ART)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (403,'Watertown, SD: Watertown Regional (ATY)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (404,'Wendover, UT: Wendover Airport (ENV)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (405,'West Palm Beach/Palm Beach, FL: Palm Beach International (PBI)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (406,'West Yellowstone, MT: Yellowstone (WYS)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (407,'White Plains, NY: Westchester County (HPN)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (408,'Wichita Falls, TX: Sheppard AFB/Wichita Falls Municipal (SPS)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (409,'Wichita, KS: Wichita Dwight D Eisenhower National (ICT)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (410,'Williston, ND: Sloulin Field International (ISN)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (411,'Wilmington, DE: New Castle (ILG)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (412,'Wilmington, NC: Wilmington International (ILM)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (413,'Worcester, MA: Worcester Regional (ORH)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (414,'Wrangell, AK: Wrangell Airport (WRG)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (415,'Yakima, WA: Yakima Air Terminal/McAllister Field (YKM)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (416,'Yakutat, AK: Yakutat Airport (YAK)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (417,'Yap, Federated States of Micronesia: Yap International (YAP)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (418,'Youngstown/Warren, OH: Youngstown-Warren Regional (YNG)');
INSERT INTO airport_ref(airport_id,airport_name) VALUES (419,'Yuma, AZ: Yuma MCAS/Yuma International (YUM)');
commit;